/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_accept[257] =
    {   0,
        0,    0,   65,   64,   63,    1,   39,   64,   36,   64,
       40,   41,   35,   31,   32,   34,    4,   51,   33,   50,
       60,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   45,   44,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   43,   64,   42,   49,    0,    0,   56,
       37,   55,   52,   53,   54,   61,    4,   60,   59,   48,
       46,   47,   60,   62,   60,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   38,    0,    0,    4,    4,    4,    4,   59,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   26,   62,   62,
       62,   62,   62,   62,   62,    0,    0,   59,   62,   62,
       62,   15,   62,   62,   11,   62,   62,   62,   62,   62,
       13,   62,   29,   62,   62,   62,   62,   62,   62,   30,
       62,   62,   62,   25,   62,    0,    0,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   27,   62,   62,   62,   62,   62,   62,    0,    0,
        3,   62,   16,   58,   62,   62,   62,   62,   62,   62,
       12,   28,   62,   62,   62,   62,   23,   22,   24,   10,

        9,    0,   62,   62,   17,   62,   62,   62,   62,   62,
       62,   62,    5,    0,   62,   62,   62,   57,   62,   62,
       62,   62,    6,    8,    7,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   19,   62,   62,   18,   62,   62,
       62,   20,   14,   62,   21,   62,   62,   62,   62,   62,
       62,   62,   62,   62,    2,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    5,    1,    6,    7,    1,    8,
        9,   10,   11,    1,   12,    1,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,    1,   15,
       16,   17,    1,   18,   19,   20,   21,   22,   23,   24,
       25,   19,   26,   19,   19,   27,   19,   28,   29,   30,
       19,   19,   31,   32,   33,   19,   34,   19,   35,   19,
       36,    1,   37,    1,   19,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   19,   54,   55,   56,   57,   58,   59,   19,
       60,   61,   62,   63,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    4,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1
    } ;

static yyconst short int yy_base[262] =
    {   0,
        0,    0,  518,  519,  519,  519,  501,   40,  500,  508,
      519,  519,  498,  497,  496,  495,   72,  494,  493,  492,
        0,  489,   48,   73,   49,   50,   51,   56,   75,   76,
       52,  519,  519,   78,   80,   84,   86,   81,   87,   88,
       82,   94,   85,  519,  443,  519,  519,  463,  466,  519,
      519,  519,  519,  519,  519,  489,  146,  488,  113,  519,
      519,  519,    0,  483,    0,   97,  111,  122,  123,  124,
      126,  151,  147,  130,  125,   99,  148,  152,  153,  157,
      160,  158,  161,  167,  171,  169,  170,  172,  174,  175,
      177,  519,  444,  451,  484,    0,  483,  180,  182,  183,

      184,  187,  188,  186,  200,  181,  204,  207,  216,  214,
      179,  218,  219,  220,  221,  223,  224,  478,  226,  222,
      228,  225,  227,  230,  229,  464,  452,  475,  235,  233,
      236,  474,  237,  250,  473,  254,  231,  257,  263,  265,
      464,  268,  460,  239,  272,  269,  273,  274,  278,  459,
      276,  280,  279,  458,  281,  433,  442,  283,  284,  286,
      287,  290,  292,  293,  291,  296,  297,  299,  302,  300,
      303,  455,  306,  305,  308,  312,  315,  321,  416,  426,
      451,  322,  450,  449,  328,  329,  332,  333,  335,  336,
      448,  447,  338,  340,  341,  342,  446,  445,  443,  440,

      519,  411,  345,  343,  434,  344,  347,  350,  351,  352,
      355,  354,  433,  395,  358,  359,  362,  431,  360,  363,
      367,  365,  430,  519,  429,  368,  370,  376,  377,  386,
      385,  391,  389,  390,  428,  392,  396,  427,  398,  399,
      401,  426,  421,  404,  234,  406,  407,  408,  410,  409,
      416,  417,  418,  420,  232,  519,  480,  121,  482,  484,
      486
    } ;

static yyconst short int yy_def[262] =
    {   0,
      256,    1,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  257,  256,  256,  256,
      258,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  256,  256,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  257,  258,  260,  256,
      256,  256,  258,  259,  258,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  256,  256,  256,  256,   57,  258,  261,  260,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  256,  256,  261,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  256,  256,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  256,  256,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      256,  256,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  256,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  256,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,    0,  256,  256,  256,  256,
      256
    } ;

static yyconst short int yy_nxt[584] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   22,   22,   25,   26,   27,   22,   28,   22,   22,
       29,   30,   22,   31,   22,   32,   33,   22,   22,   34,
       35,   22,   36,   22,   22,   37,   38,   22,   39,   40,
       22,   22,   22,   22,   41,   22,   22,   42,   43,   22,
       22,   44,   45,   46,   48,   65,   65,   65,   65,   65,
       66,   49,   56,   65,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   57,   56,   56,   56,   58,
       65,   70,   65,   65,   69,   65,   77,   65,   65,   65,

       73,   65,   65,   65,   65,   65,   71,   56,   56,   81,
       67,   65,   72,   75,   65,   78,   65,   82,   85,   74,
       76,  100,   79,   63,   68,   87,   98,   88,   65,   91,
       65,   80,   83,   56,   56,   56,   84,   89,   86,   65,
       65,   65,   65,   65,  110,   90,   56,   65,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   96,
       56,   56,   56,   58,   65,   65,  101,  108,   65,   65,
       65,  102,  109,  107,   65,   65,  103,   65,   65,  104,
      105,   56,   56,  106,   65,  111,   65,   65,   65,   65,
      113,   65,   65,   98,   65,  128,   65,   65,   65,   65,

       65,   65,  116,   65,   65,   65,  112,   56,   56,   56,
      119,  129,  117,  114,  125,  115,  133,   65,  121,  120,
      124,   65,  118,  130,   65,  135,  136,  123,  131,  132,
      134,   65,  122,   65,  140,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,  137,   65,  138,  144,  141,
      146,  147,  158,  148,  160,  150,  152,   65,  139,  142,
      154,   65,  143,  149,   65,  145,  151,  159,  161,  164,
       65,  163,   65,  153,  155,   65,   65,  169,  165,   65,
       65,   65,  166,   65,  162,   65,   65,   65,   65,  167,

       65,   65,  170,   65,   65,  181,  178,   65,   65,   65,
       65,  168,  186,   65,   65,  182,   65,   65,  177,   65,
       65,  173,   65,   65,  171,   65,  187,  175,  172,   65,
      174,  176,   65,  189,  195,  188,  183,  194,   65,   65,
      191,  185,  184,  192,  193,   65,   65,  197,  190,   65,
       65,  205,   65,   65,  198,   65,  196,   65,   65,   65,
       65,   65,   65,  200,   65,  217,  203,   65,   65,   65,
      199,   65,   65,  206,  216,   65,   65,   65,  207,   65,
       65,  220,   65,  212,   65,   65,  204,   65,  208,  210,
      215,  211,  209,   65,   65,  231,  223,  213,  230,  227,

      229,  218,   65,   65,  226,  219,   65,   65,   65,   65,
      221,  222,  225,   65,  240,   65,   65,  232,   65,  228,
      233,   65,  237,   65,   65,   65,   65,   65,  239,  251,
      234,  236,  238,   65,   65,   65,  235,   65,   65,  243,
      244,  241,  245,   65,   65,   65,   65,   65,   65,  224,
       65,   65,  248,  250,  253,  242,  214,   65,  249,  246,
       65,  247,   65,   65,   65,   65,   65,   65,   65,  252,
      202,  201,   65,  180,  179,   65,   65,   65,  254,  255,
       59,   65,   59,   59,   64,   64,   99,   99,  128,  128,
       65,   65,   65,  157,  156,   65,   97,   95,  127,  126,

       65,   97,   95,   94,   93,   92,   65,   62,   61,   60,
       55,   54,   53,   52,   51,   50,   47,  256,    3,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256
    } ;

static yyconst short int yy_chk[584] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   23,   25,   26,   27,   31,
       23,    8,   17,   28,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       24,   26,   29,   30,   25,   34,   31,   35,   38,   41,

       29,   36,   43,   37,   39,   40,   27,   17,   17,   36,
       24,   42,   28,   30,   66,   34,   76,   36,   38,   29,
       30,   66,   34,  258,   24,   40,   59,   41,   67,   43,
       59,   35,   36,   17,   17,   17,   37,   41,   39,   68,
       69,   70,   75,   71,   76,   42,   57,   74,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   73,   77,   67,   74,   72,   78,
       79,   68,   75,   73,   80,   82,   69,   81,   83,   70,
       71,   57,   57,   72,   84,   77,   86,   87,   85,   88,
       79,   89,   90,   98,   91,   99,  111,   98,  106,   99,

      100,  101,   82,  104,  102,  103,   78,   57,   57,   57,
       85,  100,   83,   80,   91,   81,  104,  105,   87,   86,
       90,  107,   84,  101,  108,  106,  107,   89,  102,  103,
      105,  110,   88,  109,  111,  112,  113,  114,  115,  120,
      116,  117,  122,  119,  123,  121,  125,  124,  137,  255,
      130,  245,  129,  131,  133,  108,  144,  109,  114,  112,
      116,  117,  129,  117,  131,  120,  122,  134,  110,  113,
      124,  136,  113,  119,  138,  115,  121,  130,  133,  137,
      139,  136,  140,  123,  125,  142,  146,  144,  138,  145,
      147,  148,  139,  151,  134,  149,  153,  152,  155,  140,

      158,  159,  145,  160,  161,  158,  155,  162,  165,  163,
      164,  142,  163,  166,  167,  159,  168,  170,  153,  169,
      171,  148,  174,  173,  146,  175,  164,  151,  147,  176,
      149,  152,  177,  166,  173,  165,  160,  171,  178,  182,
      168,  162,  161,  169,  170,  185,  186,  175,  167,  187,
      188,  186,  189,  190,  176,  193,  174,  194,  195,  196,
      204,  206,  203,  178,  207,  206,  182,  208,  209,  210,
      177,  212,  211,  187,  204,  215,  216,  219,  188,  217,
      220,  209,  222,  195,  221,  226,  185,  227,  189,  193,
      203,  194,  190,  228,  229,  222,  212,  196,  221,  217,

      220,  207,  231,  230,  216,  208,  233,  234,  232,  236,
      210,  211,  215,  237,  234,  239,  240,  226,  241,  219,
      227,  244,  231,  246,  247,  248,  250,  249,  233,  250,
      228,  230,  232,  251,  252,  253,  229,  254,  243,  239,
      240,  236,  241,  242,  238,  235,  225,  223,  218,  214,
      213,  205,  247,  249,  252,  237,  202,  200,  248,  244,
      199,  246,  198,  197,  192,  191,  184,  183,  181,  251,
      180,  179,  172,  157,  156,  154,  150,  143,  253,  254,
      257,  141,  257,  257,  259,  259,  260,  260,  261,  261,
      135,  132,  128,  127,  126,  118,   97,   95,   94,   93,

       64,   58,   56,   49,   48,   45,   22,   20,   19,   18,
       16,   15,   14,   13,   10,    9,    7,    3,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\DevMayCry.l"
#define INITIAL 0
#line 2 ".\\DevMayCry.l"
//1ª)Definições
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "banco.h"
#include "interface.h"
#include "read_file.h"

int count = 1;

#line 593 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 92 ".\\DevMayCry.l"

	//2ª)Regras


#line 749 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 257 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 519 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 96 ".\\DevMayCry.l"
{                           }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 98 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_ThisPartysGettingCrazy", "\0", count);
                        //return MAIN;
                    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 103 ".\\DevMayCry.l"
{
                        return 0;
                    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 107 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "enum", "\0", count);
                        //return NUMERO;
                        
                    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 113 ".\\DevMayCry.l"
{ 
                        tab = insert_banco(tab, yytext, "keyword_jackpot", "\0", count);
                        //return RETURN;
                    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 118 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_flockOff", "\0", count); 
                        //return REMOVE;
                    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 123 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_CatchThis", "\0", count);
                        //return TYPEDEF;
                    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 128 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_TakeThis", "\0", count);
                        //return INCLUDE;
                    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 133 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_GetSet", "\0",count);
                        //return DEFINE;
                    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_whatif", "\0", count);
                        //return IF;
                    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 143 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_NuUh", "\0", count);
                        //return ELSE;
                    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 148 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_change", "\0", count);
                        //return SWITCH;
                    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 153 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_case", "\0", count);
                        //return CASE;
                    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 158 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "repetition_ShallWeDance", "\0", count);
                        //return FOR;
                    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 163 ".\\DevMayCry.l"
{
                       tab = insert_banco(tab, yytext, "repetition_Fire", "\0", count);
                       //return WHILE;
                    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 168 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "repetition_ComeOn", "\0", count);
                        //return DO;
                    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 173 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "repetition_SILENCE", "\0", count);
                        //return BREAK;
                    }                    
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 178 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_ItsShowTime", "\0", count);
                        //return PRINTF;
                    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 182 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_WhatYouSay", "\0", count);
                        //return SCANF;
                    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 187 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_fWhatYouSay", "\0", count);
                        //return FSCANF;
                    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 192 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_fItsShowTime", "\0", count);
                        //return FPRINTF;
                    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 197 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_sizeof", "\0", count);
                        //return SIZEOF;
                    }  
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 202 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_malloc", "\0", count);
                        //return MALLOC;
                    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 207 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_struct", "\0", count);
                        //return STRUCT;
                    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 212 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_void", "\0", count);
                        //return VOID;
                    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 217 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_int", "\0", count);
                        //return INT;
                    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 222 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_float", "\0", count);
                        //return FLOAT;
                    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 227 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_double", "\0", count);
                        //return DOUBLE;
                    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 232 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_char", "\0", count);
                        //return CHAR;
                    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 237 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_long", "\0", count);
                        //return RETURN;
                    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 242 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_add", "\0", count);
                        //return ADD;
                    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 247 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_sub", "\0", count);
                        //return SUB;
                    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 252 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "atribuicao", "\0", count);
                        //return ATRIB;
                    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 257 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_div", "\0", count);
                        //return DIV;
                    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 262 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_mult", "\0", count);
                        //return MULT;
                    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 267 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_rest", "\0", count);
                        //return RESTO;
                    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 272 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_and", "\0", count);
                        //return AND;
                    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 277 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_or", "\0", count);
                        //return OR;
                    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 282 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_not", "\0", count);
                        //return NOT;
                    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 287 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_parentheses_esq", "\0", count);
                        //return PARENTESES_esq;
                    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 291 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_parentheses_dir", "\0", count);
                        //return PARENTESES_dir;
                    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 296 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_keys_dir", "\0", count);
                        //return CHAVES_dir;
                    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 300 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_keys_esq", "\0", count);
                        //return CHAVES_esq;
                    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 305 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_brackets_esq", "\0", count);
                        //return COLCHETES_esq;
                    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 309 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_brackets_dir", "\0", count);
                        //return COLCHETES_dir;
                    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 314 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "equal_comparator", "\0", count);
                        //return EQUAL;
                    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 319 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "greaterequal_comparator", "\0", count);
                        //return MAIOR_EQUAL;
                    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 324 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "lessequal_comparator", "\0", count);
                        //return MENOR_EQUAL;
                    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 329 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "notequal_comparator", "\0", count);
                        //return DIFERENTE;
                    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 334 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "greater_comparator", "\0", count);
                        //return MAIOR;
                    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 339 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "less_comparator", "\0", count);
                        //return MENOR;
                    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 344 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_add", "\0", count);
                        //return ATRIB_ADD;
                    }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 349 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_sub", "\0", count);
                        //return ATRIB_SUB;
                    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 354 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_div", "\0", count);
                        //return ATRIB_DIV;
                    }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 359 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_mult", "\0", count);
                        //return ATRIB_MULT;
                    }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 364 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_rest", "\0", count);
                        //return ATRIB_REST;
                    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 369 ".\\DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_include", "Missing #", count);
                    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 374 ".\\DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_define", "Missing #", count);
                    }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 379 ".\\DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_var", "Wrong format", count);
                    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 384 ".\\DevMayCry.l"
{
                       
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_var", "@ is not used for Ids", count);
                    }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 390 ".\\DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_num", "Wrong format", count);
                    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 395 ".\\DevMayCry.l"
{
                        tabId = insert_banco(tabId, yytext, "id", "\0", count);
                    }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 399 ".\\DevMayCry.l"
{
                        count++;
                    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 402 ".\\DevMayCry.l"
ECHO;
	YY_BREAK
#line 1337 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 257 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 257 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 256);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 402 ".\\DevMayCry.l"


int main(){
    int op;
        opcoes();
        scanf("%d%*c", &op);
        if(op){
            yyin = load_file();

            yylex();
            opcao2();
            int op2;
            scanf("%d%*c", &op2);
            if(op2){ 
                analise_lexica(tab);
                analise_lexica(tabId);
            }
            count = 1;
            free_list(tab);
            }
	return 0;
}
