/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_accept[254] =
    {   0,
        0,    0,   65,   64,    1,   63,   39,   64,   36,   64,
       40,   41,   35,   31,   32,   34,    4,   51,   33,   50,
       60,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   45,   44,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   43,   64,   42,    1,   49,    0,    0,
       56,   37,   55,   52,   53,   54,   61,    4,   60,   59,
       48,   46,   47,   60,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   38,    0,    0,    4,   59,   59,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   26,   62,   62,   62,   62,
       62,   62,   62,    0,    0,   62,   62,   62,   15,   62,
       62,   11,   62,   62,   62,   62,   62,   13,   62,   29,
       62,   62,   62,   62,   62,   62,   30,   62,   62,   62,
       25,   62,    0,    0,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   27,   62,
       62,   62,   62,   62,   62,    0,    0,    3,   62,   16,
       58,   62,   62,   62,   62,   62,   62,   12,   28,   62,
       62,   62,   62,   23,   22,   24,   10,    9,    0,   62,

       62,   17,   62,   62,   62,   62,   62,   62,   62,    5,
        0,   62,   62,   62,   57,   62,   62,   62,   62,    6,
        8,    7,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   19,   62,   62,   18,   62,   62,   62,   20,   14,
       62,   21,   62,   62,   62,   62,   62,   62,   62,   62,
       62,    2,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    7,    1,    8,
        9,   10,   11,    1,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,    1,   16,
       17,   18,    1,   19,   20,   21,   22,   23,   24,   25,
       26,   20,   27,   20,   20,   28,   20,   29,   30,   31,
       20,   20,   32,   33,   34,   20,   35,   20,   36,   20,
       37,    1,   38,    1,   20,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   20,   55,   56,   57,   58,   59,   60,   20,
       61,   62,   63,   64,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[66] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1
    } ;

static yyconst short int yy_base[259] =
    {   0,
        0,    0,  479,  480,  476,  480,  460,   40,  459,  468,
      480,  480,  457,  456,  455,  454,   55,  453,  452,  451,
        0,  448,   48,   50,   52,   57,   56,   58,   59,   62,
       60,  480,  480,   63,   61,   69,   65,   68,   71,   72,
       73,   74,   64,  480,  402,  480,  463,  480,  421,  424,
      480,  480,  480,  480,  480,  480,  447,  110,    0,   79,
      480,  480,  480,    0,  442,   96,   76,   93,   66,   78,
       99,  107,  109,  112,  113,  117,  115,  119,  120,  121,
      123,  124,  128,  126,  127,  130,  134,  129,  131,  138,
      133,  480,  403,  410,  443,  438,  141,  139,  146,  147,

      152,  142,  144,  148,  154,  158,  169,  170,  173,  174,
      177,  178,  179,  180,  181,  437,  182,  183,  184,  190,
      185,  194,  187,  423,  411,  186,  191,  195,  434,  197,
      192,  433,  220,  202,  208,  223,  188,  432,  226,  431,
      227,  228,  204,  229,  231,  234,  430,  232,  236,  237,
      419,  238,  394,  402,  239,  240,  243,  245,  247,  248,
      249,  250,  253,  255,  256,  260,  263,  257,  415,  264,
      262,  271,  272,  268,  278,  376,  386,  412,  282,  411,
      410,  279,  286,  287,  285,  288,  292,  409,  408,  294,
      295,  298,  299,  407,  406,  405,  403,  480,  374,  302,

      300,  401,  301,  304,  307,  308,  310,  315,  317,  398,
      358,  312,  316,  318,  391,  319,  326,  322,  327,  390,
      480,  389,  325,  332,  333,  334,  335,  339,  343,  347,
      348,  388,  350,  352,  387,  353,  356,  360,  386,  385,
      358,  383,  362,  364,  366,  371,  372,  368,  373,  374,
      378,  381,  480,  438,  395,  440,  442,  444
    } ;

static yyconst short int yy_def[259] =
    {   0,
      253,    1,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  254,  253,  253,  253,
      255,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  253,  253,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  254,  255,  257,
      253,  253,  253,  255,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  253,  253,  253,  253,  258,  257,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  253,  253,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  253,  253,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  253,  253,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  253,  253,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      253,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      253,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,    0,  253,  253,  253,  253,  253
    } ;

static yyconst short int yy_nxt[546] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,    4,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   22,   22,   25,   26,   27,   22,   28,   22,
       22,   29,   30,   22,   31,   22,   32,   33,   22,   22,
       34,   35,   22,   36,   22,   22,   37,   38,   22,   39,
       40,   22,   22,   22,   22,   41,   22,   22,   42,   43,
       22,   22,   44,   45,   46,   49,   59,   57,   59,   58,
       59,   66,   50,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   73,   59,   59,   67,   59,
       59,   59,   59,   96,   59,   81,   59,   59,   69,   70,

       75,   78,   68,   82,   74,   77,   85,   76,   79,   91,
       87,   59,   71,   80,   59,   72,   84,   59,   83,   88,
      101,   98,   57,   86,   58,   59,   90,   59,   59,   89,
       59,   59,   99,   59,  102,   59,  105,   59,   59,   59,
      104,   59,   59,  100,   59,   59,   59,   59,   59,   59,
      106,   59,   59,  109,  103,   96,   59,   59,  111,   59,
       59,  107,   59,  108,   59,   59,   59,  117,  126,  114,
       59,  123,   59,  130,  110,  131,   59,  133,  112,  113,
      115,  118,  116,  119,  122,  121,  127,   59,   59,  128,
      120,   59,   59,  132,  129,   59,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   59,   59,  134,   59,   59,
       59,  135,   59,   59,  155,   59,  138,  141,  143,  144,
       59,  145,   59,  164,  157,  136,   59,  147,  139,  137,
      146,  140,  149,  148,  142,  151,  156,  159,   59,  158,
      162,   59,  150,  152,   59,   59,   59,   59,  160,   59,
       59,  161,   59,  163,   59,   59,   59,   59,   59,  167,
      168,   59,  178,   59,  175,   59,   59,   59,   59,  183,
      165,   59,  179,   59,   59,   59,  166,  174,   59,  170,
       59,   59,   59,  184,  172,  169,   59,  171,  173,   59,
       59,  186,  191,  192,  180,  185,   59,   59,  188,  182,

       59,  181,  189,   59,   59,   59,   59,  187,  190,  202,
       59,  194,   59,   59,  193,  195,   59,   59,   59,   59,
       59,  197,   59,  214,  196,   59,   59,  200,   59,  203,
       59,  204,  213,   59,   59,   59,   59,   59,  201,  217,
       59,  209,  205,   59,   59,   59,  207,  208,  212,  206,
       59,   59,   59,   59,  227,  210,  224,   59,  228,  215,
      220,   59,  223,  216,  226,   59,   59,  222,   59,  218,
       59,   59,  219,  237,   59,  229,   59,  234,   59,  225,
       59,  233,   59,  230,   59,  235,   59,  236,  231,   59,
       59,   59,   59,  248,  232,  240,   59,   64,  241,   59,

      238,   59,  242,   59,   59,   59,   59,   59,   59,   59,
      245,  250,  239,  221,  243,  247,   59,  246,  244,   59,
      211,   59,  249,   59,   59,   59,   59,   59,   59,   59,
       59,  199,  198,   59,  177,  251,  176,   59,  252,   60,
       60,   60,   65,   65,   97,   97,   96,   96,   59,   59,
       59,   59,   59,  154,  153,   59,   59,   95,  125,  124,
       59,   95,   94,   93,   47,   92,   59,   63,   62,   61,
       56,   55,   54,   53,   52,   51,   48,   47,  253,    3,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,

      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253
    } ;

static yyconst short int yy_chk[546] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,   23,   17,   24,   17,
       25,   23,    8,   17,   27,   26,   28,   29,   31,   35,
       30,   34,   43,   37,   69,   29,   38,   36,   24,   39,
       40,   41,   42,   60,   67,   36,   70,   60,   25,   26,

       30,   34,   24,   36,   29,   31,   38,   30,   34,   43,
       40,   68,   27,   35,   66,   28,   37,   71,   36,   41,
       69,   66,   58,   39,   58,   72,   42,   73,   58,   41,
       74,   75,   67,   77,   70,   76,   73,   78,   79,   80,
       72,   81,   82,   68,   84,   85,   83,   88,   86,   89,
       74,   91,   87,   77,   71,   97,   90,   98,   79,   97,
      102,   75,  103,   76,   99,  100,  104,   85,   98,   82,
      101,   91,  105,  102,   78,  103,  106,  105,   80,   81,
       83,   86,   84,   87,   90,   89,   99,  107,  108,  100,
       88,  109,  110,  104,  101,  111,  112,  113,  114,  115,

      117,  118,  119,  121,  126,  123,  137,  106,  120,  127,
      131,  107,  122,  128,  126,  130,  110,  112,  114,  115,
      134,  115,  143,  137,  128,  108,  135,  118,  111,  109,
      117,  111,  120,  119,  113,  122,  127,  131,  133,  130,
      135,  136,  121,  123,  139,  141,  142,  144,  133,  145,
      148,  134,  146,  136,  149,  150,  152,  155,  156,  142,
      143,  157,  155,  158,  152,  159,  160,  161,  162,  160,
      139,  163,  156,  164,  165,  168,  141,  150,  166,  145,
      171,  167,  170,  161,  148,  144,  174,  146,  149,  172,
      173,  163,  168,  170,  157,  162,  175,  182,  165,  159,

      179,  158,  166,  185,  183,  184,  186,  164,  167,  183,
      187,  172,  190,  191,  171,  173,  192,  193,  201,  203,
      200,  175,  204,  203,  174,  205,  206,  179,  207,  184,
      212,  185,  201,  208,  213,  209,  214,  216,  182,  206,
      218,  192,  186,  223,  217,  219,  190,  191,  200,  187,
      224,  225,  226,  227,  218,  193,  214,  228,  219,  204,
      209,  229,  213,  205,  217,  230,  231,  212,  233,  207,
      234,  236,  208,  231,  237,  223,  241,  228,  238,  216,
      243,  227,  244,  224,  245,  229,  248,  230,  225,  246,
      247,  249,  250,  247,  226,  236,  251,  255,  237,  252,

      233,  242,  238,  240,  239,  235,  232,  222,  220,  215,
      244,  249,  234,  211,  241,  246,  210,  245,  243,  202,
      199,  197,  248,  196,  195,  194,  189,  188,  181,  180,
      178,  177,  176,  169,  154,  250,  153,  151,  251,  254,
      254,  254,  256,  256,  257,  257,  258,  258,  147,  140,
      138,  132,  129,  125,  124,  116,   96,   95,   94,   93,
       65,   57,   50,   49,   47,   45,   22,   20,   19,   18,
       16,   15,   14,   13,   10,    9,    7,    5,    3,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,

      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "DevMayCry.l"
#define INITIAL 0
#line 2 "DevMayCry.l"
//1ª)Definições
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "DevMayCry.tab.h"
#include "banco.h"
#include "interface.h"
#include "read_file.h"

int count = 1;

#line 583 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 93 "DevMayCry.l"

	//2ª)Regras


#line 739 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 254 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 480 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 97 "DevMayCry.l"
{ 
                        ;
                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 101 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_ThisPartysGettingCrazy", "\0", count);
                        return MAIN;
                    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 106 "DevMayCry.l"
{
                        return 0;
                    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 110 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "enum", "\0", count);
                        return NUMERO;
                        
                    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 116 "DevMayCry.l"
{ 
                        tab = insert_banco(tab, yytext, "keyword_jackpot", "\0", count);
                        return RETURN;
                    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 121 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_flockOff", "\0", count); 
                        return REMOVE;
                    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 126 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_CatchThis", "\0", count);
                        return TYPEDEF;
                    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 131 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_TakeThis", "\0", count);
                        return INCLUDE;
                    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 136 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_GetSet", "\0",count);
                        return DEFINE;
                    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 141 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_whatif", "\0", count);
                        return IF;
                    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 146 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_NuUh", "\0", count);
                        return ELSE;
                    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 151 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_change", "\0", count);
                        return SWITCH;
                    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 156 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_case", "\0", count);
                        return CASE;
                    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 161 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "repetition_ShallWeDance", "\0", count);
                        return FOR;
                    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 166 "DevMayCry.l"
{
                       tab = insert_banco(tab, yytext, "repetition_Fire", "\0", count);
                       return WHILE;
                    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 171 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "repetition_ComeOn", "\0", count);
                        return DO;
                    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 176 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "repetition_SILENCE", "\0", count);
                        return BREAK;
                    }                    
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 181 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_ItsShowTime", "\0", count);
                        return PRINTF;
                    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 185 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_WhatYouSay", "\0", count);
                        return SCANF;
                    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 190 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_fWhatYouSay", "\0", count);
                        return FSCANF;
                    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 195 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_fItsShowTime", "\0", count);
                        return FPRINTF;
                    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 200 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_sizeof", "\0", count);
                        return SIZEOF;
                    }  
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 205 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_malloc", "\0", count);
                        return MALLOC;
                    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 210 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_struct", "\0", count);
                        return STRUCT;
                    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 215 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_void", "\0", count);
                        return VOID;
                    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 220 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_int", "\0", count);
                        return INT;
                    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 225 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_float", "\0", count);
                        return FLOAT;
                    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 230 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_double", "\0", count);
                        return DOUBLE;
                    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 235 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_char", "\0", count);
                        return CHAR;
                    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 240 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_long", "\0", count);
                        return RETURN;
                    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 245 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_add", "\0", count);
                        return ADD;
                    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 250 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_sub", "\0", count);
                        return SUB;
                    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 255 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "atribuicao", "\0", count);
                        return ATRIB;
                    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 260 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_div", "\0", count);
                        return DIV;
                    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 265 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_mult", "\0", count);
                        return MULT;
                    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 270 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_rest", "\0", count);
                        return RESTO;
                    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 275 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_and", "\0", count);
                        return AND;
                    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 280 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_or", "\0", count);
                        return OR;
                    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 285 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_not", "\0", count);
                        return NOT;
                    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 290 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_parentheses_esq", "\0", count);
                        return PARENTESES_esq;
                    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 294 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_parentheses_dir", "\0", count);
                        return PARENTESES_dir;
                    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 299 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_keys_dir", "\0", count);
                        return CHAVES_dir;
                    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 303 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_keys_esq", "\0", count);
                        return CHAVES_esq;
                    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 308 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_brackets_esq", "\0", count);
                        return COLCHETES_esq;
                    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 312 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_brackets_dir", "\0", count);
                        return COLCHETES_dir;
                    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 317 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "equal_comparator", "\0", count);
                        return EQUAL;
                    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 322 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "greaterequal_comparator", "\0", count);
                        return MAIOR_EQUAL;
                    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 327 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "lessequal_comparator", "\0", count);
                        return MENOR_EQUAL;
                    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 332 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "notequal_comparator", "\0", count);
                        return DIFERENTE;
                    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 337 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "greater_comparator", "\0", count);
                        return MAIOR;
                    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 342 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "less_comparator", "\0", count);
                        return MENOR;
                    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 347 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_add", "\0", count);
                        return ATRIB_ADD;
                    }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 352 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_sub", "\0", count);
                        return ATRIB_SUB;
                    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 357 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_div", "\0", count);
                        return ATRIB_DIV;
                    }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 362 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_mult", "\0", count);
                        return ATRIB_MULT;
                    }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 367 "DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_rest", "\0", count);
                        return ATRIB_REST;
                    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 372 "DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_include", "Missing #", count);
                    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 377 "DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_define", "Missing #", count);
                    }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 382 "DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_var", "Wrong format", count);
                    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 387 "DevMayCry.l"
{
                       
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_var", "@ is not used for Ids", count);
                    }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 393 "DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_num", "Wrong format", count);
                    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 398 "DevMayCry.l"
{
                        tabId = insert_banco(tabId, yytext, "id", "\0", count);
                    }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 402 "DevMayCry.l"
{
                        count++;
                    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 405 "DevMayCry.l"
ECHO;
	YY_BREAK
#line 1329 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 254 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 254 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 253);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 405 "DevMayCry.l"

/*
int main(){
    int op;
        opcoes();
        scanf("%d%*c", &op);
        if(op){
            yyin = load_file();

            yylex();
            opcao2();
            int op2;
            scanf("%d%*c", &op2);
            if(op2){ 
                analise_lexica(tab);
                analise_lexica(tabId);
            }
            count = 1;
            free_list(tab);
            }
	return 0;
}
*/