/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
static yyconst short int yy_accept[279] =
    {   0,
        0,    0,   69,   68,    1,   67,   42,   68,   39,   68,
       43,   44,   38,   34,    3,   35,   37,    6,    2,   54,
       36,   53,   63,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   48,   47,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   46,   68,   45,    1,   52,
        0,    0,   59,   40,    0,   58,   55,   56,   57,   64,
        6,   63,   62,   51,   49,   50,   63,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   41,    0,    0,    0,    6,

       62,   62,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   28,   65,   65,   65,   65,   65,   65,   65,    0,
        0,    0,   65,   65,   65,   17,   65,   65,   13,   65,
       65,   65,   65,   65,   65,   15,   65,   31,   65,   65,
       65,   65,   65,   65,   33,   65,   65,   65,   27,   65,
        0,    0,    0,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   29,   65,
       65,   65,   65,   65,   65,    0,    0,    0,    5,   65,
       18,   61,   65,   65,   65,   32,   65,   65,   65,   14,

       30,   65,   65,   65,   65,   25,   24,   26,   12,   11,
        0,    0,   65,   65,   19,   65,   65,   65,   65,   65,
       65,   65,    7,    0,    0,   65,   65,   65,   60,   65,
       65,   65,   65,    8,   10,    0,    9,   65,   65,   65,
       65,   65,   65,    0,   65,   65,   65,   21,   65,   65,
        0,   20,   65,   65,   65,   22,    0,   16,   65,   23,
        0,   65,    0,   65,    0,   65,    0,   65,    0,   65,
        0,   65,   66,   65,   65,   65,    4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,    1,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   29,   29,   31,   32,   33,   34,   35,
       29,   36,   37,   38,   39,   29,   40,   29,   41,   29,
       42,    1,   43,    1,   29,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   29,   60,   61,   62,   63,   64,   65,   29,
       66,   67,   68,   69,   70,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[71] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    1,    3,    1,    1,    1,    1,
        4,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static yyconst short int yy_base[284] =
    {   0,
        0,    0,  512,  513,  509,  513,  491,   43,  490,  501,
      439,  513,  487,  486,  513,  485,  484,   58,  513,  483,
      482,  481,    0,  478,   52,   54,   55,   56,   59,   61,
       63,   62,   64,  513,  513,   65,   68,   78,   66,   67,
       69,   73,   70,   71,   79,  513,  429,  513,  495,  513,
      448,  451,  513,  513,  463,  513,  513,  513,  513,  477,
       81,    0,   80,  513,  513,  513,    0,  471,   82,   84,
       98,   99,  107,  110,  113,  114,  116,  115,  118,  121,
      117,  119,  120,  122,  126,  123,  128,  127,  130,  134,
      129,  132,  135,  141,  137,  513,  429,  436,  463,  472,

      466,  147,  136,  144,  146,  156,  145,  166,  157,  171,
      158,  162,  175,  177,  179,  180,  185,  181,  186,  188,
      189,  465,  190,  184,  191,  195,  194,  201,  196,  448,
      436,  445,  197,  198,  203,  461,  204,  199,  460,  206,
      200,  208,  215,  219,  210,  459,  235,  458,  238,  239,
      240,  241,  242,  245,  457,  243,  247,  246,  456,  248,
      428,  437,  438,  249,  250,  251,  252,  253,  256,  258,
      260,  261,  262,  263,  265,  268,  266,  274,  452,  273,
      269,  276,  270,  278,  279,  410,  420,  448,  448,  288,
      447,  435,  297,  299,  302,  434,  303,  305,  308,  433,

      432,  309,  310,  311,  312,  431,  430,  429,  428,  513,
      396,  377,  314,  313,  425,  316,  315,  317,  321,  322,
      323,  324,  424,  383,  374,  327,  325,  326,  421,  328,
      331,  340,  332,  420,  513,  370,  414,  333,  335,  336,
      338,  343,  359,  401,  342,  360,  363,  412,  351,  361,
      390,  407,  362,  364,  372,  405,  393,  403,  375,  402,
      396,  377,  385,  378,  385,  379,  348,  381,  408,  384,
      405,  380,  513,  388,  390,  392,  394,  513,  457,  411,
      459,  461,  463
    } ;

static yyconst short int yy_def[284] =
    {   0,
      278,    1,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  279,  278,  278,
      278,  278,  280,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  278,  278,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      279,  280,  282,  278,  278,  278,  280,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  278,  278,  278,  278,  278,

      283,  282,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  278,
      278,  278,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      278,  278,  278,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  278,  278,  278,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  281,  281,  281,  281,  281,  278,
      278,  278,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  278,  278,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  278,  278,  281,  281,  281,  281,
      281,  281,  281,  278,  281,  281,  281,  281,  281,  281,
      278,  281,  281,  281,  281,  281,  278,  281,  281,  281,
      278,  281,  278,  281,  278,  281,  278,  281,  278,  281,
      278,  281,  278,  281,  281,  281,  281,    0,  278,  278,
      278,  278,  278
    } ;

static yyconst short int yy_nxt[584] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,    4,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   24,   24,   27,   28,   24,   29,
       24,   24,   30,   24,   24,   24,   31,   32,   24,   33,
       24,   34,   35,   24,   24,   36,   37,   24,   38,   24,
       24,   39,   40,   24,   41,   42,   24,   24,   24,   24,
       43,   24,   24,   44,   45,   24,   24,   46,   47,   48,
       51,   60,   62,   61,   62,   62,   62,   69,   62,   62,
       52,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   76,   62,   60,  101,   61,   70,   62,   62,

       62,   62,   62,   73,   62,   79,   72,   85,   82,  103,
       89,   71,   80,   77,   81,   83,   91,   86,   62,   62,
       74,   92,   88,   75,   78,   84,   90,   62,   94,   95,
       62,   93,   87,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,  110,  104,   62,   62,   62,   62,
       62,  109,   62,  105,   62,   62,   62,   62,  106,  111,
      115,   62,  101,  117,   62,   62,   62,   62,  107,  133,
      108,  113,  114,  120,  112,  123,   62,   62,   62,  116,
      129,  137,   62,  125,  118,  121,   62,  119,  122,  134,
      124,   62,  128,  135,  127,   62,  140,   62,  126,   62,

       62,   62,  138,  136,   62,   62,   62,  139,   62,   62,
       62,   62,  141,  142,   62,   62,   62,   62,   62,   62,
       62,   62,  143,   62,   62,  149,   62,  146,   62,  164,
       62,  151,  152,  155,  153,   62,  166,  144,  169,   62,
      145,  147,  157,  154,  148,  156,  150,  159,  165,  168,
      174,  167,  172,  173,  170,   62,  158,  160,   62,   62,
       62,   62,   62,   62,  171,   62,   62,   62,   62,   62,
       62,   62,   62,   62,  189,  177,   62,  185,   62,  194,
       62,   62,   62,   62,  175,   62,   62,  190,   62,   62,
       62,  184,  176,   62,   62,  180,   62,  195,   62,   62,

      182,  178,  179,  181,  183,  198,  204,  191,   62,  196,
      193,  197,  200,  192,  203,  201,  202,   62,  207,   62,
      199,  206,   62,   62,  215,   62,  205,  209,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,  213,  208,
      228,   62,   62,   62,   62,   62,   62,   62,   62,  216,
      227,   62,   62,   62,  217,   62,   62,  231,   62,  222,
       62,  214,   62,   62,  218,  226,  220,  221,  243,  239,
      219,   62,  234,  223,  241,  229,  238,  242,  230,   62,
       62,   62,   62,   62,   62,  233,  232,  237,  245,  252,
      254,  246,   62,  240,  249,   62,  247,   62,   62,   62,

       62,   62,  250,  248,   62,  253,  255,  272,   62,  258,
       62,  259,   62,   67,   62,  273,  271,  269,  267,  260,
      265,  263,   62,   62,  261,   62,  256,   62,  257,  266,
      270,  275,   62,  251,   62,  268,  262,  244,  264,  274,
       62,   62,  236,  235,   62,   62,  225,  224,   62,   62,
       62,   62,   62,   62,   62,   62,  276,  277,   63,   63,
       63,   68,   68,  102,  102,  101,  101,   62,   62,  212,
      211,  210,   62,  188,  187,  186,   62,   62,   62,   62,
       62,   62,  163,  162,  161,   62,   62,  100,  132,  131,
      130,   62,  100,   99,   98,   97,   49,   96,   62,   66,

       65,   64,   59,   58,   57,   56,   55,   54,   53,   50,
       49,  278,    3,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278
    } ;

static yyconst short int yy_chk[584] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,   18,   25,   18,   26,   27,   28,   25,   18,   29,
        8,   30,   32,   31,   33,   36,   39,   40,   37,   41,
       43,   44,   31,   42,   61,   63,   61,   26,   38,   45,

       63,   61,   69,   28,   70,   32,   27,   38,   36,   69,
       40,   26,   32,   31,   33,   36,   42,   38,   71,   72,
       29,   43,   39,   30,   31,   37,   41,   73,   44,   45,
       74,   43,   38,   75,   76,   78,   77,   81,   79,   82,
       83,   80,   84,   86,   76,   70,   85,   88,   87,   91,
       89,   75,   92,   71,   90,   93,  103,   95,   72,   77,
       81,   94,  102,   83,  104,  107,  105,  102,   73,  103,
       74,   79,   80,   86,   78,   89,  106,  109,  111,   82,
       95,  107,  112,   91,   84,   87,  108,   85,   88,  104,
       90,  110,   94,  105,   93,  113,  110,  114,   92,  115,

      116,  118,  108,  106,  124,  117,  119,  109,  120,  121,
      123,  125,  111,  112,  127,  126,  129,  133,  134,  138,
      141,  128,  113,  135,  137,  118,  140,  116,  142,  133,
      145,  120,  121,  124,  121,  143,  135,  114,  140,  144,
      115,  117,  126,  123,  117,  125,  119,  128,  134,  138,
      145,  137,  143,  144,  141,  147,  127,  129,  149,  150,
      151,  152,  153,  156,  142,  154,  158,  157,  160,  164,
      165,  166,  167,  168,  164,  150,  169,  160,  170,  169,
      171,  172,  173,  174,  147,  175,  177,  165,  176,  181,
      183,  158,  149,  180,  178,  153,  182,  170,  184,  185,

      156,  151,  152,  154,  157,  173,  180,  166,  190,  171,
      168,  172,  175,  167,  178,  176,  177,  193,  183,  194,
      174,  182,  195,  197,  194,  198,  181,  185,  199,  202,
      203,  204,  205,  214,  213,  217,  216,  218,  190,  184,
      216,  219,  220,  221,  222,  227,  228,  226,  230,  195,
      214,  231,  233,  238,  197,  239,  240,  219,  241,  204,
      232,  193,  245,  242,  198,  213,  202,  203,  233,  228,
      199,  249,  222,  205,  231,  217,  227,  232,  218,  243,
      246,  250,  253,  247,  254,  221,  220,  226,  238,  245,
      247,  239,  255,  230,  242,  259,  240,  262,  264,  266,

      272,  268,  243,  241,  270,  246,  249,  270,  274,  253,
      275,  254,  276,  280,  277,  271,  269,  267,  265,  255,
      263,  261,  260,  258,  257,  256,  250,  252,  251,  264,
      268,  274,  248,  244,  237,  266,  259,  236,  262,  272,
      234,  229,  225,  224,  223,  215,  212,  211,  209,  208,
      207,  206,  201,  200,  196,  192,  275,  276,  279,  279,
      279,  281,  281,  282,  282,  283,  283,  191,  189,  188,
      187,  186,  179,  163,  162,  161,  159,  155,  148,  146,
      139,  136,  132,  131,  130,  122,  101,  100,   99,   98,
       97,   68,   60,   55,   52,   51,   49,   47,   24,   22,

       21,   20,   17,   16,   14,   13,   11,   10,    9,    7,
        5,    3,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\DevMayCry.l"
#define INITIAL 0
#line 2 ".\\DevMayCry.l"
//1ª)Definições
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "DevMayCry.tab.h"
#include "banco.h"
#include "interface.h"
#include "read_file.h"

int count = 1;

#line 599 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 99 ".\\DevMayCry.l"

	//2ª)Regras


#line 755 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 279 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 513 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 103 ".\\DevMayCry.l"
{ 
                        ;
                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 107 ".\\DevMayCry.l"
{
                    tab = insert_banco(tab,yytext,"ponto e virgula", "\0",count);
                    return PT_VRG;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 111 ".\\DevMayCry.l"
{
                    tab = insert_banco(tab,yytext,"virgula", "\0",count);
                    return VIRGULA;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 116 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_ThisPartysGettingCrazy", "\0", count);
                        return MAIN;
                    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 121 ".\\DevMayCry.l"
{
                        return 0;
                    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 125 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "enum", "\0", count);
                        return NUMERO;
                        
                    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 132 ".\\DevMayCry.l"
{ 
                        tab = insert_banco(tab, yytext, "keyword_jackpot", "\0", count);
                        return RETURN;
                    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 137 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_flockOff", "\0", count); 
                        return REMOVE;
                    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 142 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_CatchThis", "\0", count);
                        return TYPEDEF;
                    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 147 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_TakeThis", "\0", count);
                        return INCLUDE;
                    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 152 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "keyword_GetSet", "\0",count);
                        return DEFINE;
                    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 157 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_whatif", "\0", count);
                        return IF;
                    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 162 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_NuUh", "\0", count);
                        return ELSE;
                    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 167 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_change", "\0", count);
                        return SWITCH;
                    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 172 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "conditional_case", "\0", count);
                        return CASE;
                    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 177 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "repetition_ShallWeDance", "\0", count);
                        return FOR;
                    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 182 ".\\DevMayCry.l"
{
                       tab = insert_banco(tab, yytext, "repetition_Fire", "\0", count);
                       return WHILE;
                    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 187 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "repetition_ComeOn", "\0", count);
                        return DO;
                    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 192 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "repetition_SILENCE", "\0", count);
                        return BREAK;
                    }                    
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 197 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_ItsShowTime", "\0", count);
                        return PRINTF;
                    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 201 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_WhatYouSay", "\0", count);
                        return SCANF;
                    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 206 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_fWhatYouSay", "\0", count);
                        return FSCANF;
                    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 211 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_fItsShowTime", "\0", count);
                        return FPRINTF;
                    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 216 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_sizeof", "\0", count);
                        return SIZEOF;
                    }  
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 221 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "function_malloc", "\0", count);
                        return MALLOC;
                    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 226 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_struct", "\0", count);
                        return STRUCT;
                    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 231 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_void", "\0", count);
                        return VOID;
                    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 236 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_int", "\0", count);
                        return INT;
                    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 241 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_float", "\0", count);
                        return FLOAT;
                    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 246 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_double", "\0", count);
                        return DOUBLE;
                    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 251 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_char", "\0", count);
                        return CHAR;
                    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 256 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_String", "\0", count);
                        return STRING;
                    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 261 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "type_long", "\0", count);
                        return RETURN;
                    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 266 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_add", "\0", count);
                        return ADD;
                    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 271 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_sub", "\0", count);
                        return SUB;
                    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 276 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "atribuicao", "\0", count);
                        return ATRIB;
                    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 281 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_div", "\0", count);
                        return DIV;
                    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 286 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_mult", "\0", count);
                        return MULT;
                    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 291 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_rest", "\0", count);
                        return RESTO;
                    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 296 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_and", "\0", count);
                        return AND;
                    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 301 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_or", "\0", count);
                        return OR;
                    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 306 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "operator_not", "\0", count);
                        return NOT;
                    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 311 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_parentheses_esq", "\0", count);
                        return PARENTESES_esq;
                    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 315 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_parentheses_dir", "\0", count);
                        return PARENTESES_dir;
                    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 320 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_keys_dir", "\0", count);
                        return CHAVES_dir;
                    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 324 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_keys_esq", "\0", count);
                        return CHAVES_esq;
                    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 329 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_brackets_esq", "\0", count);
                        return COLCHETES_esq;
                    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 333 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "simb_brackets_dir", "\0", count);
                        return COLCHETES_dir;
                    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 338 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "equal_comparator", "\0", count);
                        return EQUAL;
                    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 343 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "greaterequal_comparator", "\0", count);
                        return MAIOR_EQUAL;
                    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 348 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "lessequal_comparator", "\0", count);
                        return MENOR_EQUAL;
                    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 353 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "notequal_comparator", "\0", count);
                        return DIFERENTE;
                    }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 358 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "greater_comparator", "\0", count);
                        return MAIOR;
                    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 363 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "less_comparator", "\0", count);
                        return MENOR;
                    }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 368 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_add", "\0", count);
                        return ATRIB_ADD;
                    }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 373 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_sub", "\0", count);
                        return ATRIB_SUB;
                    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 378 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_div", "\0", count);
                        return ATRIB_DIV;
                    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 383 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_mult", "\0", count);
                        return ATRIB_MULT;
                    }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 388 ".\\DevMayCry.l"
{
                        tab = insert_banco(tab, yytext, "accumulator_rest", "\0", count);
                        return ATRIB_REST;
                    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 393 ".\\DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_include", "Missing #", count);
                    }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 398 ".\\DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_define", "Missing #", count);
                    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 403 ".\\DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_var", "Wrong format", count);
                    }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 408 ".\\DevMayCry.l"
{
                       
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_var", "@ is not used for Ids", count);
                    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 414 ".\\DevMayCry.l"
{
                        
                        printf("Lexema: %s\nToken: %s\nWhy isn't this working? Is there something missing? Must more blood be shed?\nErro: %s\nLinha: %d\n\n", yytext, "erro_num", "Wrong format", count);
                    }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 419 ".\\DevMayCry.l"
{
                        tabId = insert_banco(tabId, yytext, "id", "\0", count);
                        return IDENTIFICADOR;
                    }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 424 ".\\DevMayCry.l"
{
                        tab = insert_banco(tabId, yytext, "String_val", "\0", count);
                        return STRING_val;
                    }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 429 ".\\DevMayCry.l"
{
                        count++;
                    }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 432 ".\\DevMayCry.l"
ECHO;
	YY_BREAK
#line 1378 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 279 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 279 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 278);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 432 ".\\DevMayCry.l"

/*
int main(){
    int op;
        opcoes();
        scanf("%d%*c", &op);
        if(op){
            yyin = load_file();

            yylex();
            opcao2();
            int op2;
            scanf("%d%*c", &op2);
            if(op2){ 
                analise_lexica(tab);
                analise_lexica(tabId);
            }
            count = 1;
            free_list(tab);
            }
	return 0;
}
*/